#!/bin/bash


dir="$1"
[ "$dir" == "" ] && dir=`pwd`
cd $dir; dir=`pwd`; cdir="${dir}-cont"
tmpfile="${cdir}/git-tmp-$$"
echo $dir $cdir $tmpfile

branch=`git-branch|grep "^\*"|awk '{print $2}'`

[ -d "$cdir" ] || git-clone $dir $cdir

while sleep 5; do 
				(
				cd "$dir";
				branch=`git-branch|grep "^\*"|awk '{print $2}'`
				( git-diff; git-diff --cached; ) > $tmpfile
				if ([ -s "${tmpfile}" ]); then
								cd "$cdir";
								git-branch |grep -q "${branch}-cont" || git-checkout --track -b ${branch}-cont ${branch}
								git-pull origin ${branch}:${branch}-cont

								git-checkout -f ${branch}
								git-apply ${tmpfile}
								git-diff ${branch}-cont > $tmpfile
								git-checkout -f ${branch}-cont
								git-apply < $tmpfile
								git-commit -am "Merge by git-cont"
				fi
				rm -f $tmpfile
				)
done
